### ISSUE TITLE
Bundle a subset of assets through webpack

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1014]
For everything but native modules, we could try using webpack to improve performance of loading (while also getting rid of the `cross-env` setup we use to set NODE_ENV to production).

**Resources**
- [Backend Apps with Webpack](http://jlongster.com/Backend-Apps-with-Webpack--Part-I)

**Comment by rgbkrk** [comment]
Based on what I'm seeing, we'll need a separate export for the main module and the renderer(s).

[electron targets](https://github.com/webpack/webpack/blob/f18989c712894bba13ebfb6dfb3f50fc44b0d12a/lib/WebpackOptionsApply.js#L119-L156)

**Comment by rgbkrk** [comment]
Success thus far:

```
$ ./node_modules/.bin/webpack
Hash: 49e499ae2ebe424b76dd
Version: webpack 1.13.2
Time: 13528ms
                    Asset     Size  Chunks             Chunk Names
    webpacked-notebook.js  9.04 MB       0  [emitted]  main
webpacked-notebook.js.map  10.9 MB       0  [emitted]  main
[1245] ./src/notebook/components ^\.\/.*$ 1.64 kB {0} [optional] [built]
    + 1250 hidden modules

WARNING in ./src/notebook/components/notebook.js
Critical dependencies:
71:6-60 the request of a dependency is an expression
 @ ./src/notebook/components/notebook.js 71:6-60

WARNING in ./app/~/github/lib/index.js
Critical dependencies:
719:22-40 the request of a dependency is an expression
 @ ./app/~/github/lib/index.js 719:22-40

WARNING in ./app/~/plotly.js/dist/plotly.js
Critical dependencies:
7:479-486 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./app/~/plotly.js/dist/plotly.js 7:479-486

WARNING in ./app/~/github/lib/generate.js
Module parse failed: /Users/kylek/code/src/github.com/nteract/nteract/app/node_modules/github/lib/generate.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (1:0)
    at Parser.pp$4.raise (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/kylek/code/src/github.com/nteract/nteract/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/kylek/code/src/github.com/nteract/nteract/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 @ ./app/~/github/lib ^\.\/.*$

ERROR in ./app/~/jmp/index.js
Module parse failed: /Users/kylek/code/src/github.com/nteract/nteract/app/node_modules/jmp/index.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (1:0)
    at Parser.pp$4.raise (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/kylek/code/src/github.com/nteract/nteract/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/kylek/code/src/github.com/nteract/nteract/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 @ ./app/~/enchannel-zmq-backend/lib/subjection.js 18:11-25
```
