### ISSUE TITLE
Random Electron Error

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1179]
Every now and the app breaks in a weird way and I get this error:

```
Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:315:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:228:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

Note that it's from Electron. No idea what causes this.

**Comment by lgeiger** [comment]
Looks like https://github.com/electron/electron/issues/7918

**Comment by rgbkrk** [comment]
I hope there is a way for us to catch this and deal with it so it doesn't break the main app.

**Comment by rgbkrk** [comment]
Better error message when it breaks since we're on a newer version of Electron!

<img width="1440" alt="screen shot 2016-11-24 at 1 56 48 pm" src="https://cloud.githubusercontent.com/assets/836375/20610409/1efb7f8c-b24e-11e6-825b-ab9549abbcf3.png">

**Comment by lgeiger** [comment]
They fixed the error reporter in https://github.com/electron/electron/pull/8003

**Comment by rgbkrk** [comment]
We've now got some try catch wrapping on some of our remote objects we were using. I'll close this as something that's slightly out of our overall control, we've mostly mitigated issues.
