### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1446]
For the 0.1.0 release I was unable to get it to package on Windows due to this error:

```
Building NSIS installer
Packaging NSIS installer for arch x64
Error: Please set perMachine to true — file associations works on Windows only if installed for all users
    at C:\Users\rgbkr\nteract\node_modules\electron-builder\src\targets\nsis.ts:326:15
    at next (native)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at NsisTarget.executeMakensis (C:\Users\rgbkr\nteract\node_modules\electron-builder\out\targets\nsis.js:412:11)
    at C:\Users\rgbkr\nteract\node_modules\electron-builder\src\targets\nsis.ts:197:60
```

I got this both on my Windows 10 machine and when running an `npm run dist:all` on my mac.

**Comment by lgeiger** [comment]
Looks like we need to change the build config: https://github.com/electron-userland/electron-builder/wiki/Options#NsisOptions
