### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1456]
I'm getting the below errors when building master:
```
> canvas@1.6.2 install C:\dev\packages\nteract\node_modules\canvas
> node-gyp rebuild


(py27) C:\dev\packages\nteract\node_modules\canvas {git}{hg}
{lamb} if not defined npm_config_node_gyp (node "C:\bin\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
c:\dev\packages\nteract\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file o r directory (compiling source file ..\src\Canvas.cc) [C:\dev\packages\nteract\node_modules\canvas\build\canvas.vcxproj]
c:\dev\packages\nteract\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file o r directory (compiling source file ..\src\CanvasGradient.cc) [C:\dev\packages\nteract\node_modules\canvas\build\canvas.vcxproj]
c:\dev\packages\nteract\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file o r directory (compiling source file ..\src\CanvasRenderingContext2d.cc) [C:\dev\packages\nteract\node_modules\canvas\build\canvas.vcx proj]
c:\dev\packages\nteract\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file o r directory (compiling source file ..\src\CanvasPattern.cc) [C:\dev\packages\nteract\node_modules\canvas\build\canvas.vcxproj]
  color.cc
  Image.cc
  ImageData.cc
  init.cc
  win_delay_load_hook.cc
c:\dev\packages\nteract\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file o r directory (compiling source file ..\src\Image.cc) [C:\dev\packages\nteract\node_modules\canvas\build\canvas.vcxproj]
c:\dev\packages\nteract\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file o r directory (compiling source file ..\src\ImageData.cc) [C:\dev\packages\nteract\node_modules\canvas\build\canvas.vcxproj]
c:\dev\packages\nteract\node_modules\canvas\src\Canvas.h(19): fatal error C1083: Cannot open include file: 'cairo.h': No such file o r directory (compiling source file ..\src\init.cc) [C:\dev\packages\nteract\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\bin\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\bin\\nodejs\\node.exe" "C:\\bin\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"

gyp ERR! cwd C:\dev\packages\nteract\node_modules\canvas
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

The build proceeds and nteract seems to work fine afterwards so I'm wondering it these errors are safe to ignore?

NB: fairly sure I had the same error last time I rebuilt so I don't think this is new.

NBB: On win64, node 7.4, npm 4.0.5 and running under py27 so gyp *should* work

**Comment by rgbkrk** [comment]
I'm getting the same error and it sadly should fail gracefully as an optional dependency for vega. I'll get this cleaned up, I'm facing it too.

**Comment by dhirschfeld** [comment]
Good to know! So long as it works I'm fine with some spurious error messages - thought I'd better check it wasn't important though.

**Comment by rgbkrk** [comment]
Let me know if this is really fixed, I'll be continuing to improve the packaging setup (while I inevitably make it worse while exporting more components).

**Comment by peggyrayzis** [comment]
@rgbkrk, idk why Github closed this automatically. I can reopen if you'd like?

**Comment by rgbkrk** [comment]
It closed automatically because I said `fixes #1456` in the PR. I _think_ it's resolved now.

**Comment by dhirschfeld** [comment]
Just a quick note to say that master fails completely to build for me
```
<SNIP>
> nteract@0.1.0 prebuild C:\dev\packages\nteract
> rimraf lib


> nteract@0.1.0 build C:\dev\packages\nteract
> npm run build:renderer && npm run build:main


> nteract@0.1.0 build:renderer C:\dev\packages\nteract
> webpack --progress --colors

Hash: d47a73c050ab5680198f
Version: webpack 1.14.0
Time: 21606ms
                Asset     Size  Chunks             Chunk Names
webpacked-notebook.js  12.4 MB       0  [emitted]  main
    + 1747 hidden modules

WARNING in ./packages/transform-plotly/~/plotly.js/dist/plotly.js
Critical dependencies:
7:479-486 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./packages/transform-plotly/~/plotly.js/dist/plotly.js 7:479-486

WARNING in ./packages/transform-vega/~/spawn-sync/lib/spawn-sync.js
Module not found: Error: Cannot resolve module 'try-thread-sleep' in C:\dev\packages\nteract\packages\transform-vega\node_modules\spawn-sync\lib
 @ ./packages/transform-vega/~/spawn-sync/lib/spawn-sync.js 10:10-37

> nteract@0.1.0 build:main C:\dev\packages\nteract
> babel src/main --out-dir ./lib/main && babel src/utils --out-dir ./lib/utils

src\main\cli.js -> lib\main\cli.js
src\main\index.js -> lib\main\index.js
src\main\kernel-specs.js -> lib\main\kernel-specs.js
src\main\kernels.js -> lib\main\kernels.js
src\main\launch.js -> lib\main\launch.js
src\main\menu.js -> lib\main\menu.js
src\main\prepare-env.js -> lib\main\prepare-env.js
src\utils\fs.js -> lib\utils\fs.js

> nteract@0.1.0 postinstall C:\dev\packages\nteract
> install-app-deps

Error: ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\acorn-jsx\package.json'
    at C:\dev\packages\nteract\node_modules\electron-builder\src\readInstalled.ts:36:21
    at Generator.next (<anonymous>)
    at LOOP (fs.js:1617:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at _readInstalled (C:\dev\packages\nteract\node_modules\electron-builder\out\readInstalled.js:85:22)
    at deps.default.map.concurrency (C:\dev\packages\nteract\node_modules\electron-builder\src\readInstalled.ts:62:105)
From previous event:
    at C:\dev\packages\nteract\node_modules\electron-builder\src\readInstalled.ts:62:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at _readInstalled (C:\dev\packages\nteract\node_modules\electron-builder\out\readInstalled.js:85:22)
    at C:\dev\packages\nteract\node_modules\electron-builder\src\readInstalled.ts:22:21
    at Generator.next (<anonymous>)
From previous event:
    at readInstalled (C:\dev\packages\nteract\node_modules\electron-builder\out\readInstalled.js:34:21)
    at C:\dev\packages\nteract\node_modules\electron-builder\src\yarn.ts:77:27
    at Generator.next (<anonymous>)
From previous event:
    at rebuild (C:\dev\packages\nteract\node_modules\electron-builder\out\yarn.js:87:22)
    at C:\dev\packages\nteract\node_modules\electron-builder\src\yarn.ts:16:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at installOrRebuild (C:\dev\packages\nteract\node_modules\electron-builder\out\yarn.js:33:21)
    at C:\dev\packages\nteract\node_modules\electron-builder\src\cli\install-app-deps.ts:31:2
    at Generator.next (<anonymous>)
From previous event:
    at main (C:\dev\packages\nteract\node_modules\electron-builder\out\cli\install-app-deps.js:35:21)
    at Object.<anonymous> (C:\dev\packages\nteract\node_modules\electron-builder\out\cli\install-app-deps.js:71:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules\7zip-bin\node_modules\7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@^1.0.3 (node_modules\7zip-bin\node_modules\7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.0.3: wanted {"os":"linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\acorn-jsx\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\babel-runtime\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\console-browserify\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\convert-source-map\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\core-js\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\electron-builder-http\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\es6-weak-map\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\falafel\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\fbjs\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\gamma\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\gl-heatmap2d\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\getpass\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\ice-cap\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\json-stable-stringify\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\mapbox-gl-style-spec\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\progress-stream\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\protocol-buffers-schema\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\qs\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\resolve-protobuf-schema\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\shelf-pack\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\unassert\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\sync-exec\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\vega\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\fbjs\node_modules\core-js\package.json'

npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\acorn-jsx\node_modules\acorn\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\electron-builder-http\node_modules\debug\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\ice-cap\node_modules\source-map\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\progress-stream\node_modules\object-keys\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\packages\nteract\node_modules\unassert\node_modules\acorn\package.json'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\bin\\nodejs\\node.exe" "C:\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! nteract@0.1.0 postinstall: `install-app-deps`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the nteract@0.1.0 postinstall script 'install-app-deps'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nteract package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     install-app-deps
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nteract
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nteract
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\packages\nteract\npm-debug.log
```

**Comment by rgbkrk** [comment]
I'll try to replicate on my Windows machine tonight.

In the meantime I recommend running:

```
$(npm bin)/lerna clean
rm -rf node_modules
npm i
```

and seeing what it reports back. We'll get this fixed.

**Comment by dhirschfeld** [comment]
Sorry, I'm not sure what you mean by `$(npm bin)/lerna clean`? 

Before building I did do a `git clean -xdf`

**Comment by rgbkrk** [comment]
Right, I'm not sure what the windows equivalent is.

Different thing to run:

```
npm install -g lerna
lerna clean
```

**Comment by dhirschfeld** [comment]
After installing lerna, doing a `lerna clean` and nuking `node_modules` it then installed cleanly! :tada: 

Thanks for your patience with noob problems!

**Comment by rgbkrk** [comment]
_phew_ I was really worried I broke things for Windows machines in the midst of the package exports.

**Comment by dhirschfeld** [comment]
I'll close this issue as I did manage to build nteract after doing a lerna clean. Feel free to reopen if you think there's anything remaining to be addressed here...
