### ISSUE TITLE
Package publishing problems

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1588]
```
$ $(npm bin)/lerna publish --force-publish @nteract/transforms-full @nteract/transform-geojson @nteract/notebook-preview @nteract/notebook-preview-demo @nteract/editor
Lerna v2.0.0-beta.38
Independent Versioning Mode
Checking for updated packages...
Comparing with: @nteract/editor@1.0.7
? Select a new version for @nteract/transforms-full (currently 1.2.0) Patch (1.2.1)

Changes:
- @nteract/transforms-full: 1.2.0 => 1.2.1

? Are you sure you want to publish the above changes? Yes

Publishing packages to npm...

NpmUtilities.publishTaggedInDir("lerna-temp", "./packages/transforms-full", )
Error: Command failed: cd /Users/kylek/code/src/github.com/nteract/nteract/packages/transforms-full && npm publish --tag lerna-temp
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! publish Failed PUT 403
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/kylek/.nvm/versions/node/v6.9.2/bin/node" "/Users/kylek/.nvm/versions/node/v6.9.2/bin/npm" "publish" "--tag" "lerna-temp"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
npm ERR! code E403

npm ERR! "You cannot publish over the previously published version 1.2.1." : @nteract/transforms-full
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kylek/code/src/github.com/nteract/nteract/packages/transforms-full/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

> @nteract/transforms-full@1.2.1 prepublish /Users/kylek/code/src/github.com/nteract/nteract/packages/transforms-full
> npm run build


> @nteract/transforms-full@1.2.1 build /Users/kylek/code/src/github.com/nteract/nteract/packages/transforms-full
> npm run build:clean && npm run build:lib && npm run build:flow


> @nteract/transforms-full@1.2.1 build:clean /Users/kylek/code/src/github.com/nteract/nteract/packages/transforms-full
> rimraf lib


> @nteract/transforms-full@1.2.1 build:lib /Users/kylek/code/src/github.com/nteract/nteract/packages/transforms-full
> babel -d lib src --ignore '**/__tests__/**'

src/index.js -> lib/index.js

> @nteract/transforms-full@1.2.1 build:flow /Users/kylek/code/src/github.com/nteract/nteract/packages/transforms-full
> flow-copy-source -v -i '**/__tests__/**' src lib

src/index.js -> lib/index.js.flow

Pushing tags to git...

To github.com:nteract/nteract.git
   886237c6..800db077  master -> master
To github.com:nteract/nteract.git
 * [new tag]           @nteract/transforms-full@1.2.1 -> @nteract/transforms-full@1.2.1
Successfully published:
 - @nteract/transforms-full@1.2.1
````

**Comment by rgbkrk** [comment]
The above is failing to actually publish to npm, yet lerna says it is successfully published.

**Comment by rgbkrk** [comment]
```
$ $(npm bin)/lerna publish --force-publish  @nteract/editor
Lerna v2.0.0-beta.38
Independent Versioning Mode
Checking for updated packages...
Comparing with: @nteract/transforms-full@1.2.2
? Select a new version for @nteract/editor (currently 1.0.7) Patch (1.0.8)
? Select a new version for @nteract/notebook-preview-demo (currently 0.1.8) Patch (0.1.9)
? Select a new version for @nteract/notebook-preview (currently 1.0.8) Patch (1.0.9)

Changes:
- @nteract/editor: 1.0.7 => 1.0.8
- @nteract/notebook-preview-demo: 0.1.8 => 0.1.9
- @nteract/notebook-preview: 1.0.8 => 1.0.9

? Are you sure you want to publish the above changes? Yes

Publishing packages to npm...
Pushing tags to git...

To github.com:nteract/nteract.git
   2f362dde..e50591b9  master -> master
To github.com:nteract/nteract.git
 * [new tag]           @nteract/editor@1.0.8 -> @nteract/editor@1.0.8
 * [new tag]           @nteract/notebook-preview-demo@0.1.9 -> @nteract/notebook-preview-demo@0.1.9
 * [new tag]           @nteract/notebook-preview@1.0.9 -> @nteract/notebook-preview@1.0.9
Successfully published:
 - @nteract/editor@1.0.8
 - @nteract/notebook-preview-demo@0.1.9
 - @nteract/notebook-preview@1.0.9
```

Still 1.0.7 on https://www.npmjs.com/package/@nteract/notebook-preview though. I'm really confused right now.

**Comment by rgbkrk** [comment]
Based on this, it seems like maybe npm is not showing the latest?

```
 ~/code/src/github.com/nteract/nteract/packages/notebook-preview$ npm publish
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

...

> @nteract/notebook-preview@1.0.9 prepublish /Users/kylek/code/src/github.com/nteract/nteract/packages/notebook-preview
> npm run build
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! "You cannot publish over the previously published version 1.0.9." : @nteract/notebook-preview

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kylek/.npm/_logs/2017-03-24T20_42_00_322Z-debug.log
```

**Comment by hzoo** [comment]
Sorry i'm pretty busy, would ask in slack.

a few things:

> "You cannot publish over the previously published version 1.2.1."

apparently it must of published 1.2.1 before so it failed again, yeah we need to fix those issues

you can use `--skip-temp-tag` now to not publish to `lerna-temp` dist tag

- the website isn't that fast to update a version:
- check unpkg or the npm registry directly: https://unpkg.com/@nteract/notebook-preview@1.0.9/
- npm view @nteract/notebook-preview dist-tags

I'm trying to do less lerna stuff so I would try our slack

**Comment by rgbkrk** [comment]
Ok, cool. Sorry for the noise @hzoo. Feel free to unsubscribe, I won't mention you again here.

**Comment by rgbkrk** [comment]
unpkg is indeed up to date, `npm view` is pretty interesting here:

```
npm view @nteract/notebook-preview dist-tags
```

**Comment by rgbkrk** [comment]
From https://status.npmjs.org/incidents/t4l5hdlgw1mq

> We are investigating lag on replicating publications to our leaf nodes as well as downstream to registry mirrors.
