### ISSUE TITLE
ZeroMQ rebuild failing on master

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1596]
```
npm ERR! Linux 4.8.12-040812-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.10.1/bin/node" "/home/travis/.nvm/versions/node/v6.10.1/lib/node_modules/npm/bin/npm-cli.js" "rebuild" "zeromq"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! zeromq@4.2.0 install: `prebuild-install || (npm run build:libzmq && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@4.2.0 install script 'prebuild-install || (npm run build:libzmq && node-gyp rebuild)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || (npm run build:libzmq && node-gyp rebuild)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zeromq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/nteract/nteract/npm-debug.log
    at ChildProcess.childProcess.once.code (/home/travis/build/nteract/nteract/node_modules/electron-builder-util/src/util.ts:134:14)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at spawn (/home/travis/build/nteract/nteract/node_modules/electron-builder-util/src/util.ts:97:3)
    at /home/travis/build/nteract/nteract/node_modules/electron-builder/src/yarn.ts:118:11
From previous event:
    at rebuild (/home/travis/build/nteract/nteract/node_modules/electron-builder/out/yarn.js:87:22)
    at /home/travis/build/nteract/nteract/node_modules/electron-builder/src/yarn.ts:16:11
    at next (native)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at installOrRebuild (/home/travis/build/nteract/nteract/node_modules/electron-builder/out/yarn.js:33:21)
    at /home/travis/build/nteract/nteract/node_modules/electron-builder/src/cli/install-app-deps.ts:31:2
    at next (native)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
From previous event:
    at main (/home/travis/build/nteract/nteract/node_modules/electron-builder/out/cli/install-app-deps.js:35:21)
    at Object.<anonymous> (/home/travis/build/nteract/nteract/node_modules/electron-builder/out/cli/install-app-deps.js:71:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^2.0.2 (node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.0.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules/7zip-bin/node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ajv-keywords@2.0.1-beta.2 requires a peer of ajv@>=5.0.4-beta.0 but none was installed.
npm ERR! Linux 4.8.12-040812-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.10.1/bin/node" "/home/travis/.nvm/versions/node/v6.10.1/bin/npm" "install"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! nteract@0.1.0 postinstall: `install-app-deps`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the nteract@0.1.0 postinstall script 'install-app-deps'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nteract package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     install-app-deps
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nteract
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nteract
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/nteract/nteract/npm-debug.log
The command "eval npm install  " failed. Retrying, 2 of 3.
```

Example log: https://travis-ci.org/nteract/nteract/jobs/216103384

Eventually it just paves ahead regardless. Not sure what's up, figured I'd post.

**Comment by lgeiger** [comment]
Interesting, the logs don't really tell me anything useful but I can't find the error in the Travis log either.

This looks more like a `electron-builder` problem though.

**Comment by rgbkrk** [comment]
[L1587](https://travis-ci.org/nteract/nteract/jobs/216103384#L1587) is a good spot.

**Comment by lgeiger** [comment]
That's interesting. [Here](https://travis-ci.org/nteract/nteract/jobs/216103384#L339) it says it installed the prebuilt successfully, but it tries to install it again during the lerna build. It may fail there because the `prebuild-install` executable isn't available then?

**Comment by rgbkrk** [comment]
Maybe we can globally install `prebuild-install` early on just to make our builds a bit faster?

**Comment by lgeiger** [comment]
It looks like we run into: https://github.com/electron-userland/electron-builder/issues/1415

**Comment by lgeiger** [comment]
This was tricky to debug since `electron-builder` didn't log to `stdout` during rebuilding (https://github.com/electron-userland/electron-builder/pull/1450). 

https://github.com/mafintosh/prebuild-install/pull/33 will fix this issue.

**Comment by lgeiger** [comment]
https://github.com/mafintosh/prebuild-install/pull/33 is shipped.

Our builds are now 2 minutes faster than before 🚀 💚

**Comment by rgbkrk** [comment]
Woo!
