### ISSUE TITLE
VPython kernel: "TypeError: require.undef is not a function"

### ISSUE THREAD

**Issue by Pugio** [nteract/archived-desktop-app#1677]
nteract 0.1.0
Python 3.6.1
jupyter 1.0.0
vpython 2.0.8

New notebook, connected to vpython kernel:
```python
from vpython import *
box()
```

Error:
```
TypeError: require.undef is not a function
    at eval (eval at runCodeHere (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339350:13), <anonymous>:1:9)
    at runCodeHere (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339350:13)
    at JavaScript.componentDidMount (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339365:6)
    at CallbackQueue.notifyAll (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:7526:23)
    at ReactReconcileTransaction.close (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:18241:27)
    at ReactReconcileTransaction.closeAll (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8705:26)
    at ReactReconcileTransaction.perform (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8652:17)
    at ReactUpdatesFlushTransaction.perform (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8639:21)
    at ReactUpdatesFlushTransaction.perform (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:7284:33)
    at Object.flushBatchedUpdates (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:7367:20)
TypeError: require.undef is not a function
    at eval (eval at runCodeHere (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339350:13), <anonymous>:1:9)
    at runCodeHere (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339350:13)
    at JavaScript.componentDidMount (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339365:6)
    at CallbackQueue.notifyAll (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:7526:23)
    at ReactReconcileTransaction.close (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:18241:27)
    at ReactReconcileTransaction.closeAll (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8705:26)
    at ReactReconcileTransaction.perform (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8652:17)
    at ReactUpdatesFlushTransaction.perform (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8639:21)
    at ReactUpdatesFlushTransaction.perform (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:7284:33)
    at Object.flushBatchedUpdates (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:7367:20)
TypeError: require.undef is not a function
    at eval (eval at runCodeHere (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339350:13), <anonymous>:1:9)
    at runCodeHere (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339350:13)
    at JavaScript.componentDidMount (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339365:6)
    at CallbackQueue.notifyAll (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:7526:23)
    at ReactReconcileTransaction.close (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:18241:27)
    at ReactReconcileTransaction.closeAll (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8705:26)
    at ReactReconcileTransaction.perform (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8652:17)
    at ReactUpdatesFlushTransaction.perform (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8639:21)
    at ReactUpdatesFlushTransaction.perform (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:7284:33)
    at Object.flushBatchedUpdates (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:7367:20)
AssertionError: path must be a string
    at Module.require (module.js:482:3)
    at require (internal/module.js:20:19)
    at eval (eval at runCodeHere (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339350:13), <anonymous>:1:1)
    at runCodeHere (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339350:13)
    at JavaScript.componentDidMount (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339365:6)
    at CallbackQueue.notifyAll (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:7526:23)
    at ReactReconcileTransaction.close (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:18241:27)
    at ReactReconcileTransaction.closeAll (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8705:26)
    at ReactReconcileTransaction.perform (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8652:17)
    at ReactUpdatesFlushTransaction.perform (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8639:21)
AssertionError: path must be a string
    at Module.require (module.js:482:3)
    at require (internal/module.js:20:19)
    at eval (eval at runCodeHere (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339350:13), <anonymous>:1:1)
    at runCodeHere (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339350:13)
    at JavaScript.componentDidMount (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339365:6)
    at CallbackQueue.notifyAll (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:7526:23)
    at ReactReconcileTransaction.close (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:18241:27)
    at ReactReconcileTransaction.closeAll (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8705:26)
    at ReactReconcileTransaction.perform (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8652:17)
    at ReactUpdatesFlushTransaction.perform (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8639:21)
AssertionError: path must be a string
    at Module.require (module.js:482:3)
    at require (internal/module.js:20:19)
    at eval (eval at runCodeHere (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339350:13), <anonymous>:1:1)
    at runCodeHere (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339350:13)
    at JavaScript.componentDidMount (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:339365:6)
    at CallbackQueue.notifyAll (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:7526:23)
    at ReactReconcileTransaction.close (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:18241:27)
    at ReactReconcileTransaction.closeAll (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8705:26)
    at ReactReconcileTransaction.perform (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8652:17)
    at ReactUpdatesFlushTransaction.perform (/Users/me/Downloads/nteract.app/Contents/Resources/app.asar/lib/webpacked-notebook.js:8639:21)
```

Can't seem to use it for VPython at all.

**Comment by jonschull** [comment]
same problem.  a shame!
