### ISSUE TITLE
Server Side Renderable Components

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1766]
I've been working with next.js and our components (again) and am running into issues with the Editor component + CodeMirror. CodeMirror wants certain globals on the page, which can be "polyfilled" but breaks things for other components. Instead of doing that I'd like to focus on making all the components server-renderable. I'll track these as individual items here:

* [x] Conditionally load CodeMirror in editor component
* [x] LaTeX component should not use `window` server side
* [x] When server side, the HTML transform "_could_" just use `dangerouslySetInnerHTML`
* [x] Fix up the plotly build
* [x] Inference for the data resource transform

**Comment by rgbkrk** [comment]
Reopening now that I'm trying more modules.

**Comment by rgbkrk** [comment]
Plotly:

```
document is not defined
ReferenceError: document is not defined
    at Object.i.addStyleRule (/Users/kylek/code/src/github.com/nteract/nteract/packages/transform-plotly/node_modules/@nteract/plotly/plotly.min.js:55:20872)
    at Object.n.1.../src/lib (/Users/kylek/code/src/github.com/nteract/nteract/packages/transform-plotly/node_modules/@nteract/plotly/plotly.min.js:7:4632)
    at i (/Users/kylek/code/src/github.com/nteract/nteract/packages/transform-plotly/node_modules/@nteract/plotly/plotly.min.js:7:555)
    at /Users/kylek/code/src/github.com/nteract/nteract/packages/transform-plotly/node_modules/@nteract/plotly/plotly.min.js:7:606
    at Object.n.666.../build/plotcss (/Users/kylek/code/src/github.com/nteract/nteract/packages/transform-plotly/node_modules/@nteract/plotly/plotly.min.js:55:269)
    at i (/Users/kylek/code/src/github.com/nteract/nteract/packages/transform-plotly/node_modules/@nteract/plotly/plotly.min.js:7:555)
    at /Users/kylek/code/src/github.com/nteract/nteract/packages/transform-plotly/node_modules/@nteract/plotly/plotly.min.js:7:606
    at Object.n.9.../src/core (/Users/kylek/code/src/github.com/nteract/nteract/packages/transform-plotly/node_modules/@nteract/plotly/plotly.min.js:7:12493)
    at i (/Users/kylek/code/src/github.com/nteract/nteract/packages/transform-plotly/node_modules/@nteract/plotly/plotly.min.js:7:555)
    at /Users/kylek/code/src/github.com/nteract/nteract/packages/transform-plotly/node_modules/@nteract/plotly/plotly.min.js:7:606
```

**Comment by rgbkrk** [comment]
We are super SSR ready nowadays, closing!
