### ISSUE TITLE
Not sure if autoupdate is working

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1932]
```
$ tail ~/Library/Logs/nteract/log.log
[2017-10-03 22:07:28.409] [info] / requested
[2017-10-03 22:07:28.414] [info] /app.zip requested
[2017-10-03 22:07:28.942] [info] download-progress listener count: 0
[2017-10-03 22:09:20.903] [info] Checking for update
[2017-10-03 22:09:22.216] [info] launching an empty notebook by default
[2017-10-03 22:09:22.328] [info] Found version 0.3.1 (url: https://github.com/nteract/nteract/releases/download/v0.3.1/nteract-0.3.1-mac.zip)
[2017-10-03 22:09:22.330] [info] Downloading update from https://github.com/nteract/nteract/releases/download/v0.3.1/nteract-0.3.1-mac.zip
[2017-10-03 22:09:22.384] [info] / requested
[2017-10-03 22:09:22.390] [info] /app.zip requested
[2017-10-03 22:09:22.652] [info] download-progress listener count: 0
```

Haven't seen the little dialog for "hey I'm ready for updates, restart me" and each time I reopen nteract it still lists it as running `0.3.0`.

**Comment by rgbkrk** [comment]
Here's a little more:

```
[2017-10-03 22:10:48.074] [info] Update for version 0.3.1 is not available (latest version: 0.3.1, downgrade is disallowed.
[2017-10-03 22:11:30.011] [info] Proxy server for native Squirrel.Mac is closed (was started to download https://github.com/nteract/nteract/releases/download/v0.3.1/nteract-0.3.1-mac.zip)
[2017-10-03 22:12:55.038] [info] Checking for update
[2017-10-03 22:12:56.096] [info] launching an empty notebook by default
[2017-10-03 22:12:57.778] [info] Update for version 0.3.1 is not available (latest version: 0.3.1, downgrade is disallowed.
```

/cc @lgeiger

**Comment by lgeiger** [comment]
`Update for version 0.3.1 is not available (latest version: 0.3.1, downgrade is disallowed` makes me think the update succeeded.

It's working fine on my system:
```
[2017-10-04 09:05:08.886] [info] Checking for update
[2017-10-04 09:05:10.993] [info] Found version 0.3.1 (url: https://github.com/nteract/nteract/releases/download/v0.3.1/nteract-0.3.1-mac.zip)
[2017-10-04 09:05:10.995] [info] Downloading update from https://github.com/nteract/nteract/releases/download/v0.3.1/nteract-0.3.1-mac.zip
[2017-10-04 09:05:11.040] [info] / requested
[2017-10-04 09:05:11.140] [info] /app.zip requested
[2017-10-04 09:05:11.561] [info] download-progress listener count: 0
[2017-10-04 09:05:12.532] [info] launching an empty notebook by default
[2017-10-04 09:05:38.095] [info] New version 0.3.1 has been downloaded
[2017-10-04 09:06:06.373] [info] Checking for update
[2017-10-04 09:06:06.480] [info] launching an empty notebook by default
[2017-10-04 09:06:08.432] [info] Update for version 0.3.1 is not available (latest version: 0.3.1, downgrade is disallowed.
```

**Comment by rgbkrk** [comment]
On my other mac, this is the current state of my logs:

```
[2017-10-03 17:38:01.504] [info] launching an empty notebook by default
[2017-10-03 17:38:01.990] [info] Update for version 0.3.0 is not available (latest version: 0.2.0, downgrade is disallowed.
[2017-10-04 09:29:53.308] [info] Checking for update
[2017-10-04 09:29:54.291] [info] launching an empty notebook by default
[2017-10-04 09:30:15.314] [info] Found version 0.3.1 (url: https://github.com/nteract/nteract/releases/download/v0.3.1/nteract-0.3.1-mac.zip)
[2017-10-04 09:30:15.315] [info] Downloading update from https://github.com/nteract/nteract/releases/download/v0.3.1/nteract-0.3.1-mac.zip
[2017-10-04 09:30:15.362] [info] / requested
[2017-10-04 09:30:15.372] [info] /app.zip requested
[2017-10-04 09:30:19.191] [info] download-progress listener count: 0
```

You know what though... I probably have all notifications off so I won't see the update finish...

**Comment by rgbkrk** [comment]
With really slow internet I may end up interrupting it by quitting it in between and then it gets into a state where it doesn't try to recover if I quit. Last night I had slow internet (just like now) and I likely quit before it was finished.

**Comment by rgbkrk** [comment]
Apparently I was still tethering this morning, and I just switched to my work wifi. Here's the error message in the logs:

```
[2017-10-04 09:43:20.068] [warn] Error: The request timed out.
[2017-10-04 09:43:20.070] [error] Error: Error: The request timed out.
[2017-10-04 09:43:20.074] [error] Error: Error: The request timed out.
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:43007:19)
    at new PromiseSpawn (/Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:44977:17)
    at /Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:45131:21
    at MacUpdater._checkForUpdates (/Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:9845:11)
    at MacUpdater.checkForUpdates (/Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:9787:39)
    at MacUpdater.checkForUpdatesAndNotify (/Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:9807:21)
    at App.initAutoUpdater (/Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:41144:32)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
```

**Comment by rgbkrk** [comment]
I'm wondering if we should introduce a menu item to "Check for updates" so we can retrigger this process if it gets in a weird state.

**Comment by rgbkrk** [comment]
Worked well after a restart!

**Comment by lgeiger** [comment]
Auto updates seem to work fine after a restart, even if the app is in a weird state.

I think we can close this.
