### ISSUE TITLE
yarn workspaces

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2039]
It did not occur to me that yarn had "workspaces" to provide the ability to do monorepo. https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/ Have you looked at this @lgeiger or @captainsafia? Does it offer benefits that would make us want to move off of lerna?

**Comment by rgbkrk** [comment]
Oooh, looks like the `yarn.lock` is only at the base and that you can `cd` into a directory to run commands as is... 🤔

**Comment by rgbkrk** [comment]
> Do Yarn Workspaces make Lerna obsolete?

> Not at all. Yarn Workspaces are easily integrated with Lerna.

**Comment by rgbkrk** [comment]
So I guess we could be using it today by adding it to our lerna setup...

```
{
  "npmClient": "yarn",
  "useWorkspaces": true
}
```

**Comment by captainsafia** [comment]
I did some research into this. I particularly like the fact that Workspaces removes duplicated dependencies. The lerna bootstrapping process takes quite some time and even gets my CPU going quite a bit.

> For avid Lerna users this is similar to bootstrapping code via the --hoist flag.

Could we add this flag to our bootstrap process?

**Comment by rgbkrk** [comment]
> Could we add this flag to our bootstrap process?

Yeah, we used to use it. @lgeiger swapped it out due to an issue with electron builder -- he told me that it's since been fixed so we can switch back. I'll see if I can make our repo switch over to this today.

**Comment by rgbkrk** [comment]
The only major annoyance I'm seeing for us + adoption is that we have to make contributors install yarn and set this:

```
yarn config set workspaces-experimental true
```

**Comment by rgbkrk** [comment]
I've changed everything locally that is necessary, time to push a PR and see what folks think. 😬

**Comment by rgbkrk** [comment]
<details>
<summary>Current run</summary>

```
$ yarn
yarn install v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning sinon > build > wrench@1.3.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
warning workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > rx-jupyter > codecov > request > node-uuid@1.4.8: Use uuid module instead
warning workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract-on-jupyter > plotly.js > mapbox-gl > feature-filter@2.2.0: This package has been merged into the 'mapbox-gl-style-spec' package
warning workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract-on-jupyter > plotly.js > mapbox-gl > mapbox-gl-function@1.3.0: This package has been merged with the 'mapbox-gl-style-spec' package
warning workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract-on-jupyter > plotly.js > mapbox-gl > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
warning workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract-on-jupyter > plotly.js > mapbox-gl > shelf-pack@1.1.0: This module is now under the @mapbox namespace: install @mapbox/shelf-pack instead
warning workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract-on-jupyter > plotly.js > mapbox-gl > unitbezier@0.0.0: This module has moved: switch to @mapbox/unitbezier
warning workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract-on-jupyter > plotly.js > mapbox-gl > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract-on-jupyter > plotly.js > mapbox-gl > vector-tile > point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
warning workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract-on-jupyter > plotly.js > mapbox-gl > vt-pbf > vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
warning workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract-on-jupyter > plotly.js > mapbox-gl > whoots-js@2.1.0: This module is now under the @mapbox namespace: install @mapbox/whoots-js instead
warning workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract > electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
warning workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > @nteract/notebook-preview-demo > next > glob-promise > semantic-release > npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
warning workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract-on-jupyter > plotly.js > color-rgba > color-space > husl@5.0.3: Project renamed to HSLuv
warning workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract-on-jupyter > plotly.js > mapbox-gl > geojson-rewind > geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead
[2/4] 🚚  Fetching packages...
info 7zip-bin-win@2.1.1: The platform "darwin" is incompatible with this module.
info "7zip-bin-win@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-linux@1.1.0: The platform "darwin" is incompatible with this module.
info "7zip-bin-linux@1.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
warning " > babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
warning " > chai-immutable@1.6.0" has incorrect peer dependency "chai@>= 2.0.0 < 4".
warning "workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > fs-observable@2.0.1" has unmet peer dependency "rxjs@^5.5.0".
warning "workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > @nteract/core > commonmark-react-renderer@4.3.3" has incorrect peer dependency "commonmark@^0.27.0 || ^0.26.0 || ^0.24.0".
warning "workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > @nteract/core > react-redux@5.0.6" has unmet peer dependency "redux@^2.0.0 || ^3.0.0".
warning "workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > @nteract/core > react-simple-dropdown@3.2.0" has incorrect peer dependency "react@0.14.x || 15.x".
warning "workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > @nteract/core > react-simple-dropdown@3.2.0" has incorrect peer dependency "react-dom@0.14.x || 15.x".
warning "workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract > redux-observable@0.16.0" has unmet peer dependency "rxjs@^5.0.0".
warning "workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract-on-jupyter > next@3.2.2" has incorrect peer dependency "react@^15.5.4".
warning "workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract-on-jupyter > next@3.2.2" has incorrect peer dependency "react-dom@^15.5.4".
warning "workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > @nteract/transforms > react-json-tree@0.10.9" has incorrect peer dependency "react@^15.0.0".
warning "workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > @nteract/transforms > react-json-tree@0.10.9" has incorrect peer dependency "react-dom@^15.0.0".
warning "workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > @nteract/notebook-preview-demo > next > glob-promise@3.2.0" has unmet peer dependency "glob@*".
warning "workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract-on-jupyter > next > glob-promise@3.1.0" has unmet peer dependency "glob@*".
warning "workspace-aggregator-bed363b4-48f1-45c4-bc33-7009207579ff > nteract-on-jupyter > next > styled-jsx@1.0.11" has incorrect peer dependency "react@15.x.x".
[4/4] 📃  Building fresh packages...
[-/9] ⠠ waiting...
[-/9] ⠠ waiting...
[-/9] ⠠ waiting...
[-/9] ⠠ waiting...
error /Users/kylek/code/src/github.com/nteract/nteract/node_modules/nteract: Command failed.
Exit code: 255
Command: electron-builder install-app-deps
Arguments:
Directory: /Users/kylek/code/src/github.com/nteract/nteract/node_modules/nteract
Output:
electron-builder 19.45.0
Error: Unresolved node modules: follow-redirects, https-proxy-agent, mime, netrc, jp-kernel, zeromq, lodash
    at /Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/src/util/packageDependencies.ts:112:19
From previous event:
    at Collector.resolveUnresolvedHoisted (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/out/util/packageDependencies.js:208:11)
    at /Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/src/util/packageDependencies.ts:88:18
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Collector.collect (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/out/util/packageDependencies.js:156:11)
    at computeDependencies (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/src/util/packageDependencies.ts:51:26)
    at /Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/src/util/packageDependencies.ts:46:28
    at Generator.next (<anonymous>)
From previous event:
    at getProductionDependencies (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/out/util/packageDependencies.js:29:21)
    at Lazy [as creator] (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/src/util/packageDependencies.ts:40:25)
    at Lazy.get value [as value] (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/lazy-val/src/main.ts:18:23)
    at /Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/src/util/yarn.ts:123:65
    at Generator.next (<anonymous>)
From previous event:
    at rebuild (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/out/util/yarn.js:94:22)
    at /Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/src/util/yarn.ts:21:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at installOrRebuild (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/out/util/yarn.js:32:21)
    at /Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/src/cli/install-app-deps.ts:58:42
    at Generator.next (<anonymous>)
From previous event:
    at installAppDeps (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/out/cli/install-app-deps.js:51:21)
    at then (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/out/cli/cli.js:127:128)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.args [as handler] (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/out/cli/cli.js:127:117)
    at Object.runCommand (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/node_modules/yargs/yargs.js:1013:30)
    at Object.get [as argv] (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/kylek/code/src/github.com/nteract/nteract/node_modules/electron-builder/out/cli/cli.js:123:441)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

</details>

**Comment by rgbkrk** [comment]
Just a little update on our current package dependencies that need to be addressed for hoisting:

```
lerna WARN EHOIST_ROOT_VERSION The repository root depends on mkdirp@0.5.1, which differs from the more common mkdirp@^0.5.1.
lerna WARN EHOIST_PKG_VERSION "fs-observable" package depends on mkdirp@^0.5.1, which differs from the hoisted mkdirp@0.5.1.
lerna WARN EHOIST_ROOT_VERSION The repository root depends on nbschema@0.1.0, which differs from the more common nbschema@^0.1.0.
lerna WARN EHOIST_PKG_VERSION "@nteract/commuter" package depends on nbschema@^0.1.0, which differs from the hoisted nbschema@0.1.0.
lerna WARN EHOIST_ROOT_VERSION The repository root depends on immutable@4.0.0-rc.9, which differs from the more common immutable@^4.0.0-rc.9.
lerna WARN EHOIST_PKG_VERSION "@nteract/commutable" package depends on immutable@^4.0.0-rc.9, which differs from the hoisted immutable@4.0.0-rc.9.
lerna WARN EHOIST_ROOT_VERSION The repository root depends on react@16.2.0, which differs from the more common react@^16.0.0.
lerna WARN EHOIST_PKG_VERSION "@nteract/commuter-frontend" package depends on react@^16.2.0, which differs from the hoisted react@16.2.0.
lerna WARN EHOIST_PKG_VERSION "@nteract/play" package depends on react@^16.2.0, which differs from the hoisted react@16.2.0.
lerna WARN EHOIST_PKG_VERSION "@nteract/showcase" package depends on react@^16.0.0, which differs from the hoisted react@16.2.0.
lerna WARN EHOIST_PKG_VERSION "nteract-on-jupyter" package depends on react@^16.0.0, which differs from the hoisted react@16.2.0.
lerna WARN EHOIST_ROOT_VERSION The repository root depends on react-dom@16.2.0, which differs from the more common react-dom@^16.0.0.
lerna WARN EHOIST_PKG_VERSION "@nteract/commuter-frontend" package depends on react-dom@^16.2.0, which differs from the hoisted react-dom@16.2.0.
lerna WARN EHOIST_PKG_VERSION "@nteract/play" package depends on react-dom@^16.2.0, which differs from the hoisted react-dom@16.2.0.
lerna WARN EHOIST_PKG_VERSION "@nteract/showcase" package depends on react-dom@^16.0.0, which differs from the hoisted react-dom@16.2.0.
lerna WARN EHOIST_PKG_VERSION "nteract-on-jupyter" package depends on react-dom@^16.0.0, which differs from the hoisted react-dom@16.2.0.
lerna WARN EHOIST_ROOT_VERSION The repository root depends on styled-jsx@2.2.1, which differs from the more common styled-jsx@^2.1.3.
lerna WARN EHOIST_PKG_VERSION "@nteract/showcase" package depends on styled-jsx@^2.1.3, which differs from the hoisted styled-jsx@2.2.1.
lerna WARN EHOIST_ROOT_VERSION The repository root depends on rxjs@5.5.6, which differs from the more common rxjs@^5.5.0.
lerna WARN EHOIST_PKG_VERSION "@nteract/core" package depends on rxjs@^5.5.0, which differs from the hoisted rxjs@5.5.6.
lerna WARN EHOIST_PKG_VERSION "@nteract/editor" package depends on rxjs@^5.5.0, which differs from the hoisted rxjs@5.5.6.
lerna WARN EHOIST_PKG_VERSION "enchannel-zmq-backend" package depends on rxjs@^5.5.0, which differs from the hoisted rxjs@5.5.6.
lerna WARN EHOIST_PKG_VERSION "@nteract/messaging" package depends on rxjs@^5.5.0, which differs from the hoisted rxjs@5.5.6.
lerna WARN EHOIST_PKG_VERSION "rx-binder" package depends on rxjs@^5.5.0, which differs from the hoisted rxjs@5.5.6.
lerna WARN EHOIST_PKG_VERSION "rx-jupyter" package depends on rxjs@^5.5.0, which differs from the hoisted rxjs@5.5.6.
lerna WARN EHOIST_PKG_VERSION "@nteract/showcase" package depends on rxjs@^5.5.0, which differs from the hoisted rxjs@5.5.6.
lerna WARN EHOIST_PKG_VERSION "nteract-on-jupyter" package depends on rxjs@^5.5.0, which differs from the hoisted rxjs@5.5.6.
lerna WARN EHOIST_PKG_VERSION "@nteract/play" package depends on rxjs@^5.5.2, which differs from the hoisted rxjs@5.5.6.
lerna WARN EHOIST_PKG_VERSION "nteract" package depends on escape-carriage@1.2.0, which differs from the hoisted escape-carriage@^1.2.0.
lerna WARN EHOIST_PKG_VERSION "@nteract/notebook-on-next" package depends on isomorphic-fetch@2.2.1, which differs from the hoisted isomorphic-fetch@^2.2.1.
lerna WARN EHOIST_PKG_VERSION "@nteract/notebook-on-next" package depends on next@4.2.1, which differs from the hoisted next@^4.1.4.
lerna WARN EHOIST_PKG_VERSION "nteract-on-jupyter" package depends on next@4.2.1, which differs from the hoisted next@^4.1.4.
lerna WARN EHOIST_PKG_VERSION "nteract" package depends on commonmark@0.28.1, which differs from the hoisted commonmark@^0.28.0.
lerna WARN EHOIST_PKG_VERSION "nteract" package depends on commonmark-react-renderer@4.3.4, which differs from the hoisted commonmark-react-renderer@^4.3.3.
lerna WARN EHOIST_PKG_VERSION "@nteract/core" package depends on date-fns@^1.28.5, which differs from the hoisted date-fns@1.29.0.
lerna WARN EHOIST_PKG_VERSION "@nteract/core" package depends on react-dnd@^2.4.0, which differs from the hoisted react-dnd@2.5.4.
lerna WARN EHOIST_PKG_VERSION "@nteract/core" package depends on react-dnd-html5-backend@^2.4.1, which differs from the hoisted react-dnd-html5-backend@2.5.4.
lerna WARN EHOIST_PKG_VERSION "nteract" package depends on react-redux@5.0.6, which differs from the hoisted react-redux@^5.0.5.
lerna WARN EHOIST_PKG_VERSION "@nteract/notebook-on-next" package depends on react-redux@5.0.6, which differs from the hoisted react-redux@^5.0.5.
lerna WARN EHOIST_PKG_VERSION "@nteract/play" package depends on react-redux@^5.0.6, which differs from the hoisted react-redux@^5.0.5.
lerna WARN EHOIST_PKG_VERSION "@nteract/core" package depends on redux@^3.7.0, which differs from the hoisted redux@3.7.2.
lerna WARN EHOIST_PKG_VERSION "nteract-on-jupyter" package depends on redux@^3.7.0, which differs from the hoisted redux@3.7.2.
lerna WARN EHOIST_PKG_VERSION "@nteract/play" package depends on redux@^3.7.2, which differs from the hoisted redux@3.7.2.
lerna WARN EHOIST_PKG_VERSION "nteract" package depends on lodash@4.17.4, which differs from the hoisted lodash@^4.17.4.
lerna WARN EHOIST_PKG_VERSION "@nteract/commuter" package depends on fs-extra@^5.0.0, which differs from the hoisted fs-extra@5.0.0.
lerna WARN EHOIST_PKG_VERSION "nteract" package depends on react-notification-system@0.2.16, which differs from the hoisted react-notification-system@^0.2.14.
lerna WARN EHOIST_PKG_VERSION "nteract" package depends on redux-observable@0.17.0, which differs from the hoisted redux-observable@^0.17.0.
lerna WARN EHOIST_PKG_VERSION "@nteract/notebook-on-next" package depends on redux-observable@0.17.0, which differs from the hoisted redux-observable@^0.17.0.
```

**Comment by lgeiger** [comment]
We may be able to retry this with the latest release of electron builder: https://github.com/electron-userland/electron-builder/releases/tag/v20.6.0

**Comment by rgbkrk** [comment]
Nice!

**Comment by rgbkrk** [comment]
We are now on yarn workspaces!
