### ISSUE TITLE
Post release woes

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2277]
Just some scattered notes while I fix this mega release

```
⸨░░░░░░░░░░░░░░░░░░⸩ ⠴ npmPublish: verb execScript No prepublish script found at /Users/kyle/code/src/github.com/nteract/nteract/applications/jupyter-extension/nteract_on_jupyter
```

```
lerna ERR! publish Retrying failed publish: nteract
lerna ERR! publish Retrying failed publish: nteract
⸨         ░░░░░░░░░⸩ ⠦ npmPublish: ERR! publish Retrying failed publish: nteract
```

```
⸨         ░░░░░░░░░⸩ ⠙ npmPublish: ERR! publish Retrying failed publish: nteract
lerna ERR! publish Retrying failed publish: nteract
lerna ERR! publish Ran out of retries while publishing nteract Error: Command failed: npm publish --tag latest
lerna ERR! publish npm ERR! "toString()" failed
lerna ERR! publish
lerna ERR! publish npm ERR! A complete log of this run can be found in:
lerna ERR! publish npm ERR!     /Users/kyle/.npm/_logs/2017-12-31T17_29_06_478Z-debug.log
lerna ERR! publish
lerna ERR! publish     at Promise.all.then.arr (/Users/kyle/.nvm/versions/node/v8.0.0/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR! publish     at <anonymous>
lerna ERR! publish     at process._tickCallback (internal/process/next_tick.js:169:7)
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm publish --tag latest
lerna ERR! npm ERR! "toString()" failed
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /Users/kyle/.npm/_logs/2017-12-31T17_29_06_478Z-debug.log
lerna ERR!
lerna ERR!     at Promise.all.then.arr (/Users/kyle/.nvm/versions/node/v8.0.0/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
(node:14331) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 16): [object Object]
(node:14331) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

<details>
<summary>debug log</summary>

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/kyle/.nvm/versions/node/v8.0.0/bin/node',
1 verbose cli   '/Users/kyle/.nvm/versions/node/v8.0.0/bin/npm',
1 verbose cli   'publish',
1 verbose cli   '--tag',
1 verbose cli   'latest' ]
2 info using npm@5.4.2
3 info using node@v8.0.0
4 verbose npm-session 18d501ecaba4e68e
5 verbose publish [ '.' ]
6 info lifecycle nteract@0.5.0~prepublish: nteract@0.5.0
7 info lifecycle nteract@0.5.0~prepare: nteract@0.5.0
8 info lifecycle nteract@0.5.0~prepublishOnly: nteract@0.5.0
9 info lifecycle nteract@0.5.0~prepack: nteract@0.5.0
10 info lifecycle nteract@0.5.0~postpack: nteract@0.5.0
11 verbose getPublishConfig undefined
12 silly mapToRegistry name nteract
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data { type: 'tag',
15 silly mapToRegistry   registry: true,
15 silly mapToRegistry   where: undefined,
15 silly mapToRegistry   raw: 'nteract',
15 silly mapToRegistry   name: 'nteract',
15 silly mapToRegistry   escapedName: 'nteract',
15 silly mapToRegistry   scope: undefined,
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   saveSpec: null,
15 silly mapToRegistry   fetchSpec: 'latest',
15 silly mapToRegistry   gitRange: undefined,
15 silly mapToRegistry   gitCommittish: undefined,
15 silly mapToRegistry   hosted: undefined }
16 silly mapToRegistry uri https://registry.npmjs.org/nteract
17 verbose publish registryBase https://registry.npmjs.org/
18 silly publish uploading /var/folders/d6/28470sgd1zd5d8l86z_b26lm0000gn/T/npm-16613-c5911801/tmp/fromDir-faf3278d/package.tgz
19 verbose stack Error: "toString()" failed
19 verbose stack     at stringSlice (buffer.js:538:45)
19 verbose stack     at Buffer.toString (buffer.js:593:10)
19 verbose stack     at RegClient.putFirst (/Users/kyle/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:103:23)
19 verbose stack     at /Users/kyle/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:54:14
19 verbose stack     at ConcatStream.<anonymous> (/Users/kyle/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/index.js:36:43)
19 verbose stack     at emitNone (events.js:110:20)
19 verbose stack     at ConcatStream.emit (events.js:207:7)
19 verbose stack     at finishMaybe (/Users/kyle/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:607:14)
19 verbose stack     at endWritable (/Users/kyle/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:615:3)
19 verbose stack     at ConcatStream.Writable.end (/Users/kyle/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:571:41)
19 verbose stack     at ReadStream.onend (_stream_readable.js:582:10)
19 verbose stack     at Object.onceWrapper (events.js:312:19)
19 verbose stack     at emitNone (events.js:110:20)
19 verbose stack     at ReadStream.emit (events.js:207:7)
19 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
19 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
19 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
20 verbose cwd /Users/kyle/code/src/github.com/nteract/nteract/applications/desktop
21 verbose Darwin 17.3.0
22 verbose argv "/Users/kyle/.nvm/versions/node/v8.0.0/bin/node" "/Users/kyle/.nvm/versions/node/v8.0.0/bin/npm" "publish" "--tag" "latest"
23 verbose node v8.0.0
24 verbose npm  v5.4.2
25 error "toString()" failed
26 verbose exit [ 1, true ]
```

</details>

**Comment by rgbkrk** [comment]
It looks like the tags created above totally failed...

**Comment by rgbkrk** [comment]
I have the tags locally, and the commit. It looks like they weren't published to npm so I can "easily" revert this locally.

I'm going to hang out with my kids and workout, I'll be back on this in a couple hours.

**Comment by rgbkrk** [comment]
annnnd nevermind -- some published: https://www.npmjs.com/package/ansi-to-react

**Comment by rgbkrk** [comment]
Shipped:

```
     - ansi-to-react@2.0.2
     - @nteract/dropdown-menu@0.0.2
     - @nteract/octicons@0.0.2
     - @nteract/timeago@3.4.4
     - @nteract/transform-dataresource@2.0.3
     - @nteract/transform-geojson@3.0.2
     - @nteract/transform-model-debug@3.0.2
     - @nteract/transform-plotly@3.1.1
     - @nteract/transform-vdom@2.0.3
     - @nteract/transform-vega@3.0.2
     - @nteract/types@1.0.1
     - @nteract/nbextension@0.3.3
     - rx-binder@1.0.5
     - rx-jupyter@2.3.0
     - fs-observable@2.0.3
```

Failed to ship:

```
     - @nteract/commutable@3.0.0
     - @nteract/commuter-frontend@3.0.0
     - @nteract/core@1.0.0
     - @nteract/display-area@3.1.1
     - @nteract/editor@5.0.0
     - enchannel-zmq-backend@6.0.0
     - @nteract/messaging@3.0.0
     - @nteract/notebook-preview@5.0.0
     - @nteract/transforms-full@4.0.1
     - @nteract/transforms@3.1.0
     - @nteract/commuter@3.0.0
     - nteract@0.5.0
     - @nteract/notebook-on-next@1.0.1
     - @nteract/play@1.1.0
     - @nteract/showcase@0.1.0
     - nteract-on-jupyter@1.1.7
```

**Comment by rgbkrk** [comment]
Updated:

Shipped:

```
     - ansi-to-react@2.0.2
     - @nteract/dropdown-menu@0.0.2
     - @nteract/octicons@0.0.2
     - @nteract/timeago@3.4.4
     - @nteract/transform-dataresource@2.0.3
     - @nteract/transform-geojson@3.0.2
     - @nteract/transform-model-debug@3.0.2
     - @nteract/transform-plotly@3.1.1
     - @nteract/transform-vdom@2.0.3
     - @nteract/transform-vega@3.0.2
     - @nteract/types@1.0.1
     - @nteract/nbextension@0.3.3
     - rx-binder@1.0.5
     - rx-jupyter@2.3.0
     - fs-observable@2.0.3
     # new contenders
     - enchannel-zmq-backend@6.0.1
     - @nteract/commutable@3.0.1
     - @nteract/messaging@3.0.1
     - @nteract/transforms@3.1.0
     - @nteract/display-area@3.1.3
     - @nteract/transforms-full@4.0.3
```

Failed to ship:

```
     - @nteract/commuter-frontend@3.0.0
     - @nteract/core@1.0.0
     - @nteract/editor@5.0.0
     - @nteract/notebook-preview@5.0.0
     - @nteract/commuter@3.0.0
     - nteract@0.5.0
     - @nteract/notebook-on-next@1.0.1
     - @nteract/play@1.1.0
     - @nteract/showcase@0.1.0
     - nteract-on-jupyter@1.1.7
```

**Comment by rgbkrk** [comment]
```
lerna publish --force-publish=* --ignore nteract
```

is my new saving grace

**Comment by rgbkrk** [comment]
New failures with the above approach:

```
lerna ERR! publish Retrying failed publish: @nteract/commuter-frontend
```

I'll get each of the issues fixes and update all release docs. Sorry about all the patch releases, folks. 🚧 👷

**Comment by rgbkrk** [comment]
If I had to guess while waiting on the current publish, commuter-frontend is failing because of mathjax asset copying.

**Comment by rgbkrk** [comment]
Sure enough:

```
lerna ERR! > @nteract/commuter-frontend@3.0.4 prepublish .
lerna ERR! > npm run copy-static
lerna ERR!
lerna ERR!
lerna ERR! > @nteract/commuter-frontend@3.0.4 copy-static /Users/kyle/code/src/github.com/nteract/nteract/packages/commuter-frontend
lerna ERR! > npm run copy-mathjax
lerna ERR!
lerna ERR!
lerna ERR! > @nteract/commuter-frontend@3.0.4 precopy-mathjax /Users/kyle/code/src/github.com/nteract/nteract/packages/commuter-frontend
lerna ERR! > mkdirp static/mathjax-electron

... and a bunch more logs
```

**Comment by rgbkrk** [comment]
Oooook, it looks like the ship of _all_ the packages and apps is all set except for the desktop app. I've got to run but I'll get that one out soon after lunch.

**Comment by rgbkrk** [comment]
Oh wait, nevermind that... commuter-frontend broke because of uglify. Let me see if I can fix up that next.js setup.

**Comment by rgbkrk** [comment]
Successful full publish with:

```
lerna publish --force-publish=* --ignore nteract --ignore @nteract/commuter-frontend
```

Now to figure out what's up with those two... 🔜

**Comment by rgbkrk** [comment]
What even is this?

```
No prepublish script found at /Users/kyle/code/src/github.com/nteract/nteract/applications/desktop/scripts/prepublish.js
```

We don't have a scripts directory with the desktop app...

**Comment by rgbkrk** [comment]
Woo! `nteract` "published". Stage 1 done, now on to the real publish of the built app!

**Comment by rgbkrk** [comment]
I'm thinking now that our top-level `npm run publish` command should be something ships everything _but_ applications. I'll then do the desktop release separately.

**Comment by rgbkrk** [comment]
Ok I've fixed all the packages (I hope), do I try to ship as is, with patch releases across the board?

**Comment by rgbkrk** [comment]
More notes from the trenches:

* ~~`npm install` from the root should not run the desktop app's webpack build~~ Nevermind, that was me making a mess

**Comment by rgbkrk** [comment]
I just made a release of all the packages with no problems just now so I'm closing this. We're in a good state now.

Some things I did to double check that publish was going to go ok:

```
lerna run prepare
lerna run prepublishOnly
```

This forced making sure that all the publish related steps work appropriately.
