### ISSUE TITLE
No Syntax-Highlighting in 0.5.5

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#2356]
Everything is black, white or gray :(

![image](https://user-images.githubusercontent.com/881019/34807272-8e80ea48-f6d3-11e7-9367-8ebbf309bf8a.png)

**Comment by rgbkrk** [comment]
Anything in the dev console?

**Comment by dhirschfeld** [comment]
Hmm, heisenbug - can't repro at the moment. But will check the console if it crops up again...

**Comment by dhirschfeld** [comment]
NB: When I open nteract I see the same blank error as in #2346. And maybe when switching/restarting the kernel too.

After opening nteract and seeing the error the console looks like:
![image](https://user-images.githubusercontent.com/881019/34811826-93e28102-f6ee-11e7-942f-3aaea7a7e43b.png)

```
Objecterror: truepayload: Error: no parent_header.msg_id on message
    at e._next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/webpacked-notebook.js:1:545819)
    at e.__tryOrUnsub (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:8517)
    at e.next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:7795)
    at e._next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:6850)
    at e.next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:6521)
    at e._next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:6850)
    at e.next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:6521)
    at e.next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:11531)
    at e._next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:6850)
    at e.next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:6521)message: "no parent_header.msg_id on message"stack: "Error: no parent_header.msg_id on message↵    at e._next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/webpacked-notebook.js:1:545819)↵    at e.__tryOrUnsub (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:8517)↵    at e.next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:7795)↵    at e._next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:6850)↵    at e.next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:6521)↵    at e._next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:6850)↵    at e.next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:6521)↵    at e.next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:11531)↵    at e._next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:6850)↵    at e.next (file:///C:/Program%20Files/nteract/resources/app.asar/lib/vendor.js:1:6521)"__proto__: Objectconstructor: function Error()message: ""name: "Error"toString: function toString()__proto__: Objecttype: "ERROR"__proto__: Objectconstructor: function Object()hasOwnProperty: function hasOwnProperty()isPrototypeOf: function isPrototypeOf()propertyIsEnumerable: function propertyIsEnumerable()toLocaleString: function toLocaleString()toString: function toString()valueOf: function valueOf()__defineGetter__: function __defineGetter__()__defineSetter__: function __defineSetter__()__lookupGetter__: function __lookupGetter__()__lookupSetter__: function __lookupSetter__()get __proto__: function __proto__()set __proto__: function __proto__()
(anonymous) @ webpacked-notebook.js:1
```

**Comment by rgbkrk** [comment]
Hmmm, I'm going to change our current behavior of erroring the stream when the `parent_header.msg_id` is not present to instead just log and ignore the message. We'll still want to do better handling and reporting of this.

**Comment by rgbkrk** [comment]
Oh hey! Because of our logging I was able to find out when this happens. _Sometimes_ the first status message from IPython has no parent header because there _isn't_ a parent header (it's the first message and also distant from any request).

![screen shot 2018-01-21 at 9 18 30 am](https://user-images.githubusercontent.com/836375/35196826-4b4cee8c-fe8c-11e7-84b9-300fedc415af.png)
