### ISSUE TITLE
Error on starting nteract 

### ISSUE THREAD

**Issue by betatim** [nteract/archived-desktop-app#298]
With 82b0ad695b `nteract` starts but shows an error:

```
Failed to compile /Users/thead/git/nteract/nteract/src/notebook/index.html: Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1364:5)
    at /Users/thead/git/nteract/nteract/node_modules/babel-core/lib/transformation/file/options/option-manager.js:353:36
    at /Users/thead/git/nteract/nteract/node_modules/babel-core/lib/transformation/file/options/option-manager.js:375:22
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/thead/git/nteract/nteract/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/Users/thead/git/nteract/nteract/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/Users/thead/git/nteract/nteract/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.init (/Users/thead/git/nteract/nteract/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
    at File.initOptions (/Users/thead/git/nteract/nteract/node_modules/babel-core/lib/transformation/file/index.js:194:75)
```

Clean checkout of master, node 5.4.x, mac os x, then run `npm install`, `npm run start` and get the above error. Will do some more investigating tomorrow.

**Comment by rgbkrk** [comment]
I went ahead and completely nuked all of my installed node versions from `nvm` (as well as all the `node_modules`), removed `node_modules` within nteract, installed a fresh node `v5.10.1` using `nvm`, then installed nteract. nteract launched and worked perfectly with a notebook as arg and with no args.

A few tips:
- `npm cache clean -f` - make sure your cache is clean since you bumped your version of node
- Rely on [nvm](https://github.com/creationix/nvm) for node version management

**Comment by jdfreder** [comment]
I agree with what @rgbkrk is hinting, it sounds like an API change in the node path packages which suggests nteract is running in an older node than you expect.

**Comment by betatim** [comment]
Switched to `nvm` and still no luck. Had several problems while `npm install` was running when it printed `cb() not called` as well as a sha verification failing. Those I put down to shaky internet. Successfully installed everything again but get same error when starting `nteract`.

(this is more a note for myself than a question)

**Comment by betatim** [comment]
I never tracked down what caused this but it is fixed "as if by magic" now so closing.
