### ISSUE TITLE
commuter - crash or abnormal repose when connect from browser at Windows 7, Python 2.7.15, Node 8.9.3

### ISSUE THREAD

**Issue by tkmktime** [nteract/archived-desktop-app#3270]
With code of Aug.29,2018,  at Windows 7 and Python 2.7.15 environment, I met abnormal case.   

With Chrome, it was crashed  with traceback:
CONFIGURED DISCOVERY none
Running in the current working directory,  C:\projectg\sfpa_client\intro
[Wed Aug 29 2018 08:57:05 GMT-0400 (Eastern Daylight Time)] INFO Node env: production
[Wed Aug 29 2018 08:57:05 GMT-0400 (Eastern Daylight Time)] INFO Commuter server listening on port 4000
::1 - - [29/Aug/2018:12:57:15 +0000] "GET / HTTP/1.1" 302 -

c:\ProgramData\Miniconda2\envs\py27\node_modules\@nteract\commuter\node_modules\src\observable\dom\AjaxObservable.ts:467
          return JSON.parse((xhr as any).responseText || 'null');
                      ^
SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseXhrResponse (c:\ProgramData\Miniconda2\envs\py27\node_modules\@nteract\commuter\node_modules\src\observable\dom\AjaxObservable.ts:467:23)

    at new AjaxError (c:\ProgramData\Miniconda2\envs\py27\node_modules\@nteract\commuter\node_modules\src\observable\dom\AjaxObservable.ts:454:21)
    at exports.XMLHttpRequest.xhrReadyStateChange [as onreadystatechange] (c:\ProgramData\Miniconda2\envs\py27\node_modules\@nteract\commuter\node_modules\src\observable\dom\AjaxObservable.ts:378:28)
    at exports.XMLHttpRequest.dispatchEvent (c:\ProgramData\Miniconda2\envs\py27\node_modules\@nteract\commuter\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:591:25)
    at setState (c:\ProgramData\Miniconda2\envs\py27\node_modules\@nteract\commuter\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:610:14)
    at exports.XMLHttpRequest.handleError (c:\ProgramData\Miniconda2\envs\py27\node_modules\@nteract\commuter\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:532:5)
    at ClientRequest.errorHandler (c:\ProgramData\Miniconda2\envs\py27\node_modules\@nteract\commuter\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:459:14)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)

With Firefox, abnormal display: 
ÿ
its console log :
 [Show/hide message details.] Failed to fetch content: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
TopStoriesFeed.jsm:109
1535502506675	Toolkit.Telemetry	WARN	TelemetryStorage::_scanArchive - have seen this id before: 0ffedca3-f47d-4de8-8c6b-8e4246666c3c, overwrite: false
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xul
The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.

I  have installed nodejs by using conda, and its version is 8.9.3.

Could you help me to resolve this case ?

Thanks

**Comment by rgbkrk** [comment]
Did you setup commuter in dev mode or a global install? We've fixed a bunch of Windows related issues and I'd love to know if this is still an issue.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue if you are still having trouble. Thanks! 🌻
