### ISSUE TITLE
Commuter fails to launch in Ubuntu 16.04

### ISSUE THREAD

**Issue by ir0nt0ad** [nteract/archived-desktop-app#3420]
(installed with npm according to the docs):

Throws the following:
CONFIGURED DISCOVERY none
Running in the current working directory,  <current-dir>
/usr/local/lib/node_modules/@nteract/commuter/node_modules/@nteract/webpack-configurator/index.js:13
const { aliases } = require("./aliases");
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/@nteract/commuter/next.config.js:2:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by rgbkrk** [comment]
We're dependent on node 8.10+, this might be the issue it's having with the destructuring syntax.
