### ISSUE TITLE
Unforeseen styled-jsx issues in typescript land

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#3849]
`styled-jsx` inline CSS _must_ be transpiled using the babel config. Now that (many) components are migrated to typescript, this isn't happening. Now they're ending up in one of two bad spots -- they're being created as regular `style` elements with a useless `jsx` property or they're getting used as template literals which generate errors upon use:

```js
> css`a { color: green; }`
Error: styled-jsx/css: if you are getting this error it means that your `css` tagged template literals were not transpiled.
    at notTranspiledError (/Users/kylek/code/src/github.com/nteract/nteract-ext/node_modules/styled-jsx/css.js:2:9)
    at css (/Users/kylek/code/src/github.com/nteract/nteract-ext/node_modules/styled-jsx/css.js:9:3)
```

I've done a bit of digging prior to opening this issue to see if we can migrate our current components to effectively using the transpiled API. Effectively that comes out to something like this:

```jsx
import Style from "styled-jsx/style";

export const Cell = props => {
  const children = props.children;
  const styleId = generateIdFromSomewhere();

  const jsxClassName = `.jsx-${styleId}`;

  return (
    <div
      className={`${jsxClassName} cell ${props.isSelected ? "focused" : ""} ${
        props._hovered ? "overrideHover" : ""
      }`}
    >
      <Style
        styleId={styleId}
        css={`
          .cell${jsxClassName} {
            position: relative;
            background: var(--theme-cell-bg, white);
            transition: all 0.1s ease-in-out;
          }
          ...more
        `}
      />
      {children}
    </div>
  );
};
```

I haven't yet figured out how I could turn the css string into the prefixed one here (there must be some internal styled-jsx API I could use).

All this to say... We need to figure out a direction now. Open questions:

* Should we switch back to babel, yet using the typescript plugin for babel, so we can run the styled-jsx transform?
* Should we migrate to styled-components or typestyle?
* What's another direction we could take?

Apologies for not seeing this one in advance and not having a clear direction for us to go yet.

**Comment by rgbkrk** [comment]
This is now done. We've switched to `styled-components`!
