### ISSUE TITLE
@nteract/presentational-components ships with ES5 incompatible dependencies

### ISSUE THREAD

**Issue by mpacer** [nteract/archived-desktop-app#4663]
**Application or Package Used**
@nteract/presentational-components

**Describe the bug**
@nteract/presentational-components 3.0.8 includes dependencies that are not ES5 compatible, specifically by including react-syntax-highlighter which has explicit `export` statements 
```
/apps/commuter/node_modules/react-syntax-highlighter/dist/esm/styles/prism/vs.js:1
export default {
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/apps/commuter/node_modules/@nteract/presentational-components/lib/syntax-highlighter/index.js:15:30)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

I think this may be related

https://github.com/nteract/nteract/blob/cbeb83b1abe8c0c3227945b8ab5c124e9489893e/package.json#L108

**Comment by wadethestealth** [comment]
This should be solved by the latest patch.
