### ISSUE TITLE
Installation fails on Ubuntu 16.04 64bit

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#708]
The new release is broken for linux. So I tried installing it the dev way:

`npm install` emitted two warning which shouldn't be major:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

`npm run start` starts the window and displays the following error:

```
Could not locate the bindings file. Tried: 
/home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/build/zmq.node
/home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/build/Debug/zmq.node
/home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/build/Release/zmq.node
/home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/out/Debug/zmq.node
/home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/Debug/zmq.node
/home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/out/Release/zmq.node
 /home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/Release/zmq.node
/home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/build/default/zmq.node
/home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/compiled/6.1.0/linux/x64/zmq.node
```

`npm test` errors to:

```
> nteract@0.0.8 test /home/lukasgeiger/code/nteract
> npm run test:unit


> nteract@0.0.8 test:unit /home/lukasgeiger/code/nteract
> mocha -r test/setup.js --compilers js:babel-core/register 'test/renderer/**/*.js'

/home/lukasgeiger/code/nteract/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/build/zmq.node
 → /home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/build/Debug/zmq.node
 → /home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/build/Release/zmq.node
 → /home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/out/Debug/zmq.node
 → /home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/Debug/zmq.node
 → /home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/out/Release/zmq.node
 → /home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/Release/zmq.node
 → /home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/build/default/zmq.node
 → /home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/compiled/6.5.0/linux/x64/zmq.node
    at bindings (/home/lukasgeiger/code/nteract/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/lib/index.js:6:30)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module._load (/home/lukasgeiger/code/nteract/node_modules/mock-require/index.js:14:22)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lukasgeiger/code/nteract/node_modules/zmq-prebuilt/index.js:2:18)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module._load (/home/lukasgeiger/code/nteract/node_modules/mock-require/index.js:14:22)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lukasgeiger/code/nteract/node_modules/@captainsafia/jmp-prebuilt/index.js:39:11)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module._load (/home/lukasgeiger/code/nteract/node_modules/mock-require/index.js:14:22)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lukasgeiger/code/nteract/node_modules/enchannel-zmq-backend/lib/subjection.js:18:20)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module._load (/home/lukasgeiger/code/nteract/node_modules/mock-require/index.js:14:22)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lukasgeiger/code/nteract/node_modules/enchannel-zmq-backend/lib/index.js:15:19)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module._load (/home/lukasgeiger/code/nteract/node_modules/mock-require/index.js:14:22)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lukasgeiger/code/nteract/src/notebook/epics/kernelLaunch.js:7:1)
    at Module._compile (module.js:556:32)
    at loader (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module._load (/home/lukasgeiger/code/nteract/node_modules/mock-require/index.js:14:22)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lukasgeiger/code/nteract/src/notebook/epics/index.js:6:1)
    at Module._compile (module.js:556:32)
    at loader (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module._load (/home/lukasgeiger/code/nteract/node_modules/mock-require/index.js:14:22)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lukasgeiger/code/nteract/src/notebook/middlewares.js:5:1)
    at Module._compile (module.js:556:32)
    at loader (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module._load (/home/lukasgeiger/code/nteract/node_modules/mock-require/index.js:14:22)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lukasgeiger/code/nteract/src/notebook/store.js:5:1)
    at Module._compile (module.js:556:32)
    at loader (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module._load (/home/lukasgeiger/code/nteract/node_modules/mock-require/index.js:14:22)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lukasgeiger/code/nteract/test/utils.js:12:1)
    at Module._compile (module.js:556:32)
    at loader (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module._load (/home/lukasgeiger/code/nteract/node_modules/mock-require/index.js:14:22)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lukasgeiger/code/nteract/test/renderer/actions_spec.js:8:1)
    at Module._compile (module.js:556:32)
    at loader (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/lukasgeiger/code/nteract/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module._load (/home/lukasgeiger/code/nteract/node_modules/mock-require/index.js:14:22)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /home/lukasgeiger/code/nteract/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/lukasgeiger/code/nteract/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/home/lukasgeiger/code/nteract/node_modules/mocha/lib/mocha.js:485:10)
    at Object.<anonymous> (/home/lukasgeiger/code/nteract/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test:unit"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! nteract@0.0.8 test:unit: `mocha -r test/setup.js --compilers js:babel-core/register 'test/renderer/**/*.js'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nteract@0.0.8 test:unit script 'mocha -r test/setup.js --compilers js:babel-core/register 'test/renderer/**/*.js''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nteract package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha -r test/setup.js --compilers js:babel-core/register 'test/renderer/**/*.js'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nteract
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nteract
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lukasgeiger/code/nteract/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

I can start debugging this next week.

**Comment by lgeiger** [comment]
OK this isn't that bad.
The `node_modules/zmq-prebuild/build` folder is missing. If I additionally run `npm install zmq-prebuilt` it will be created and everything works.

**Comment by lgeiger** [comment]
I completely nuked everything, did a fresh install and cannot reproduce this issue anymore :tada:.

Maybe giving the VM more RAM for doing the installation did the trick.
Anyway, I'm happy to close this one.

**Comment by rgbkrk** [comment]
Yay!

Something else from chat discovered by @lgeiger: `electron-packager` doesn't grab the prebuilds for the target machine - the OS X zmq prebuilt was packaged with the Linux version.

Solution (if I do the next release): build it in Docker
