### ISSUE TITLE
Provide better error when kernel doesn't spawn

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#897]
Error:

``` js
events.js:160 
Uncaught Error: spawn /home/jdetlefs/github/nteract/bin/python3 ENOENT
```

On my machine I would think that I could run 

``` js
const spawnteract = require('spawnteract')

spawnteract.launch('python3').then(kernel => {
     console.log(kernel.config.ip + ':' + kernel.config.shell_port);
});
function cleanup(kernel) {
       kernel.spawn.kill();
       fs.unlink(kernel.connectionFile);
 }
```

But I get this error: 

``` js
127.0.0.1:9002
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn /home/jdetlefs/github/nteract/bin/python3 ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any idea what's going on?

**Comment by jdetle** [comment]
Contents of my `kernel.json` file

```
  1 {
  2  "language": "python",
  3  "display_name": "Python 3",
  4  "argv": [
  5   "/home/jdetlefs/github/nteract/bin/python3",
  6   "-m",
  7   "ipykernel",
  8   "-f",
  9   "{connection_file}"
 10  ]
 11 }      
```

**Comment by rgbkrk** [comment]
That's a peculiar location for the python3 kernel. Was that installed in a `virtualenv`?

**Comment by jdetle** [comment]
Very possible

**Comment by rgbkrk** [comment]
Does the path to that python3 still exist?

**Comment by jdetle** [comment]
No, but I installed more kernels 

```
 { name: 'python2',
     files: 
      [ '/usr/local/share/jupyter/kernels/python2/kernel.json',
        '/usr/local/share/jupyter/kernels/python2/logo-32x32.png',
        '/usr/local/share/jupyter/kernels/python2/logo-64x64.png' ],
     resources_dir: '/usr/local/share/jupyter/kernels/python2',
     spec: { display_name: 'Python 2', language: 'python', argv: [Object] } },
```

**Comment by jdetle** [comment]
This still doesnt work,

```
  1 {
  2  "display_name": "Python 2",
  3  "language": "python",
  4  "argv": [
  5   "/usr/bin/python",
  6   "-m",
  7   "ipykernel",
  8   "-f",
  9   "{connection_file}"
 10  ]
 11 }
```

**Comment by jdetle** [comment]
I omitted this error because I thought it wasn't relevant, but I also get this error.

```
Subscriber.ts:210 
Uncaught Error: EACCES: permission denied,
 open '/home/jdetlefs/.config/nteract/theme.json'
```

**Comment by jdetle** [comment]
Okay so things are working now. I nuked the kernels and reinstalled. There still might be an issue here with how we handle a broken kernelspec, but I'm not sure. Closing for now.

**Comment by rgbkrk** [comment]
What's the jupyter notebook report for kernelspecs that are no longer valid.

**Comment by jdetle** [comment]
It was this one 

```
   1 {
  2  "language": "python",
  3  "display_name": "Python 3",
  4  "argv": [
  5   "/home/jdetlefs/github/nteract/bin/python3",
  6   "-m",
  7   "ipykernel",
  8   "-f",
  9   "{connection_file}"
 10  ]
 11 }
```

because this path didn't actually exist. Unfortunately I was stupid and deleted both of the kernels.

**Comment by rgbkrk** [comment]
That's ok, seems like something easy to reproduce by writing another direct kernelspec that is invalid.

**Comment by jdetle** [comment]
Alright, so it seems like a broken kernelspec causes this error `Uncaught Error: spawn /usr/bin/python2.71`.
To reproduce, change the path of the kernel.json file to anything that doesn't exist. In my case I changed `/usr/bin/python2.7`, to `/usr/bin/python2.71`.

**Comment by jdetle** [comment]
``` javascript
#!/usr/bin/env node
const spawnteract = require('spawnteract')

spawnteract.launch('python2').then(kernel => {
        // Returns
        // kernel.spawn <-- The running process, from child_process.spawn(...)
        // kernel.connectionFile <-- Connection file path
        // kernel.config <-- Connection information from the file

        // Print the ip address and port for the shell channel
         console.log(kernel.config.ip + ':' + kernel.config.shell_port);
});

function cleanup(kernel) {
     kernel.spawn.kill();
     fs.unlink(kernel.connectionFile);
}
```

works fine with this python 2 kernelspec installed per the normal instructions: (kernel.json file)

``` json
  1 {
  2  "display_name": "Python 2",
  3  "language": "python",
  4  "argv": [
  5   "/usr/bin/python2.7",
  6   "-m",
  7   "ipykernel",
  8   "-f",
  9   "{connection_file}"
 10  ]
 11 }
```

but if I change that spawnteract script and run it with my python3 kernel: (kernel.json file)

``` json
  1 {
  2  "language": "python",
  3  "display_name": "Python 3",
  4  "argv": [
  5   "/usr/local/bin/python3.5",
  6   "-m",
  7   "ipykernel",
  8   "-f",
  9   "{connection_file}"
 10  ]
 11 }
```

 I get the same error: 

```
Error: spawn /home/jdetlefs/github/nteract/bin/python3 ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jdetle** [comment]
@rgbkrk at the cost of fixing this quickly I'm going to try to take a stab at closing this issue.

**Comment by rgbkrk** [comment]
How's this look now for you? The message now bubbles up to a notification.

**Comment by jdetle** [comment]
I'll check it out when I get home.
